spring:
  profiles:
    include: aws,s3

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: create
logging.level:
  org.hibernate.SQL: debug